apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-application
  labels:
    app: java-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-application
  template:
    metadata:
      labels:
        app: java-application
    spec:
      containers:
      - name: java-application
        image: krishnalakamsani/java-application:4
        ports:
        - containerPort: 8080
