apiVersion: v1
kind: Service
metadata:
  name: java-application-service
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30500
  selector:
    app: java-application
